version: '3'

services:
  api:
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres
    ports:
      - '127.0.0.1:27826:5432'
    environment:
      - POSTGRES_DB=uforika
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
