export const AUTH_ERRORS_INVALID_SIGNATURE = 'INVALID_SIGNATURE';
export const AUTH_ERRORS_INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
export const AUTH_ERRORS_REFRESH_TOKEN_IS_REVOKED = 'REFRESH_TOKEN_IS_REVOKED';
